/**
 * Patient compartment membership.
 *
 * The compartment table in metadata/compartment/patient.json (generated by
 * scripts/generatePatientCompartment.js from the FHIR R4 Patient
 * CompartmentDefinition) maps each resource type to the dot paths at which a
 * Reference to a Patient may appear.
 *
 * Author: John Grimes
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const { _comment, ...compartmentPaths } = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', '..', 'metadata', 'compartment', 'patient.json'), 'utf8'),
)

/**
 * Collect `reference` strings found by walking a dot path, fanning out through
 * any arrays encountered along the way.
 *
 * @param {unknown} node the current node.
 * @param {string[]} segments the remaining path segments.
 * @param {string[]} out the accumulator.
 */
function collectReferences(node, segments, out) {
  if (node === null || node === undefined) return
  if (Array.isArray(node)) {
    for (const item of node) collectReferences(item, segments, out)
    return
  }
  if (typeof node !== 'object') return
  if (segments.length === 0) {
    if (typeof node.reference === 'string') out.push(node.reference)
    return
  }
  collectReferences(node[segments[0]], segments.slice(1), out)
}

/**
 * Return every reference string found at the resource type's Patient
 * compartment paths. For a Patient resource, `Patient/<id>` is also included so
 * that the patient is a member of its own compartment.
 *
 * @param {object} resource a FHIR resource.
 * @returns {string[]} the reference strings; empty for resource types outside the compartment.
 */
export function patientCompartmentReferences(resource) {
  const references = []
  if (resource.resourceType === 'Patient' && resource.id !== undefined) {
    references.push(`Patient/${resource.id}`)
  }
  for (const dotPath of compartmentPaths[resource.resourceType] || []) {
    collectReferences(resource, dotPath.split('.'), references)
  }
  return references
}

/**
 * Reduce a reference string to its trailing `Type/id` segment, so that absolute
 * references such as `http://host/fhir/Patient/x` compare equal to `Patient/x`.
 *
 * @param {string} reference a reference string.
 * @returns {string} the relative form.
 */
function relativeReference(reference) {
  const parts = reference.split('/')
  return parts.length > 2 ? parts.slice(-2).join('/') : reference
}

/**
 * Test whether a resource belongs to the compartment of any of the given patients.
 *
 * @param {object} resource a FHIR resource.
 * @param {Set<string>} patientRefs the set of `Patient/<id>` strings defining the compartment.
 * @returns {boolean} true when the resource references any of the patients.
 */
export function inPatientCompartment(resource, patientRefs) {
  return patientCompartmentReferences(resource).some(
    (reference) => patientRefs.has(reference) || patientRefs.has(relativeReference(reference)),
  )
}
